name: Daily Data Update

on:
  schedule:
    - cron: '0 6 * * 1-5'  # Run at 6 AM UTC, Monday to Friday
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run data update
      run: python tech_data.py
      
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add stock_data/
        git diff --staged --quiet || git commit -m "Daily data update - $(date)"
        git push
